{
  "components": [
    {
      "id": "metric_bolt",
      "includes": ["BOSL/constants.scad", "BOSL/metric_screws.scad"],
      "module": "metric_bolt",
      "params": [
        { "name": "size", "type": "int", "unit": "mm", "required": true, "synonyms": ["m", "size", "diameter", "thread", "m-size"] },
        { "name": "l", "type": "float", "unit": "mm", "required": true, "synonyms": ["length", "long", "l"] },
        { "name": "coarse", "type": "bool", "default": true, "synonyms": ["coarse", "course", "fine"] }
      ],
      "intent_keywords": ["bolt", "screw", "cap", "fastener"]
    },
    {
      "id": "metric_nut",
      "includes": ["BOSL/constants.scad", "BOSL/metric_screws.scad"],
      "module": "metric_nut",
      "params": [
        { "name": "size", "type": "int", "unit": "mm", "required": true, "synonyms": ["m", "size", "diameter", "thread", "m-size"] }
      ],
      "intent_keywords": ["nut", "hex nut", "lock nut"]
    },
    {
      "id": "cuboid",
      "includes": ["BOSL/constants.scad", "BOSL/shapes.scad"],
      "module": "cuboid",
      "params": [
        { "name": "size", "type": "float[]", "unit": "mm", "required": true, "synonyms": ["size", "dimensions", "length width height", "lwh"] },
        { "name": "fillet", "type": "float", "unit": "mm", "required": false, "synonyms": ["fillet", "round", "radius"] },
        { "name": "chamfer", "type": "float", "unit": "mm", "required": false, "synonyms": ["chamfer", "bevel"] }
      ],
      "intent_keywords": ["cuboid", "cube", "box", "rectangular"]
    },
    {
      "id": "cyl",
      "includes": ["BOSL/constants.scad", "BOSL/shapes.scad"],
      "module": "cyl",
      "params": [
        { "name": "l", "type": "float", "unit": "mm", "required": true, "synonyms": ["length", "l", "h", "long"] },
        { "name": "d", "type": "float", "unit": "mm", "required": true, "synonyms": ["diameter", "d", "od"] }
      ],
      "intent_keywords": ["cyl", "cylinder", "tube", "pipe"]
    },
    {
      "id": "trapezoidal_threaded_rod",
      "includes": ["BOSL/constants.scad", "BOSL/threading.scad"],
      "module": "trapezoidal_threaded_rod",
      "params": [
        { "name": "d",             "type": "float", "unit": "mm",      "required": true,  "synonyms": ["diameter", "d", "od", "width"] },
        { "name": "l",             "type": "float", "unit": "mm",      "required": true,  "synonyms": ["length", "l", "long"] },
        { "name": "pitch",         "type": "float", "unit": "mm",      "required": true,  "synonyms": ["pitch", "lead", "thread pitch"] },
        { "name": "thread_depth",  "type": "float", "unit": "mm",      "required": false, "default": "pitch/2", "synonyms": ["depth", "thread depth"] },
        { "name": "thread_angle",  "type": "float", "unit": "degree",  "required": false, "default": 14.5,      "synonyms": ["angle", "pressure angle", "profile angle"] }
      ],
      "intent_keywords": [
        "threaded rod",
        "threaded-rod",
        "trapezoidal",
        "acme",
        "acme rod",
        "lead screw",
        "leadscrew",
        "square thread",
        "screw rod",
        "thread"
      ]
    },
    {
      "id": "sphere",
      "module": "sphere",
      "includes": [],
      "params": [
        { "name": "r", "type": "float", "unit": "mm", "required": true, "synonyms": ["radius","size", "r="] }
      ],
      "intent_keywords": ["sphere", "ball", "circle"]
    },
    {
      "id": "gear",
      "includes": ["BOSL/constants.scad", "BOSL/involute_gears.scad"],
      "module": "gear",
      "params": [
        { "name": "mm_per_tooth",   "type": "float", "unit": "mm", "required": true,  "synonyms": ["circular pitch", "circular_pitch", "mm per tooth", "mm-per-tooth", "cp"] },
        { "name": "number_of_teeth","type": "int",   "unit": "",   "required": true,  "synonyms": ["teeth", "tooth_count", "z"] },
        { "name": "thickness",      "type": "float", "unit": "mm", "required": true,  "synonyms": ["thickness", "face width", "width"] },
        { "name": "hole_diameter",  "type": "float", "unit": "mm", "required": true,  "synonyms": ["bore", "inner diameter", "id", "shaft hole"] }
      ],
      "intent_keywords": ["gear", "spur gear", "helical gear", "involute", "cog", "toothed wheel"]
    },
    {
      "id": "tray",
      "includes": ["tray.scad"],
      "module": "tray",
      "params": [
        { "name": "dimensions",     "type": "float[]", "unit": "mm", "required": true,  "synonyms": ["size", "dimensions", "length width height", "lwh"] },
        { "name": "thickness",      "type": "float",   "unit": "mm", "required": false, "default": 2,     "synonyms": ["wall thickness", "thickness", "wall"] },
        { "name": "n_columns",      "type": "int",     "unit": "",   "required": false, "default": 1,     "synonyms": ["columns", "col", "c"] },
        { "name": "n_rows",         "type": "int",     "unit": "",   "required": false, "default": 1,     "synonyms": ["rows", "row", "r"] },
        { "name": "curved",         "type": "bool",    "unit": "",   "required": false, "default": true,  "synonyms": ["curved", "rounded", "smooth"] },
        { "name": "bottom_thickness", "type": "float", "unit": "mm", "required": false, "default": "thickness", "synonyms": ["bottom", "base thickness"] },
        { "name": "dividers_height", "type": "float",  "unit": "mm", "required": false, "default": "height", "synonyms": ["divider height", "separator height"] },
        { "name": "dividers_thickness", "type": "float", "unit": "mm", "required": false, "default": "thickness", "synonyms": ["divider thickness", "separator thickness"] }
      ],
      "intent_keywords": ["tray", "organizer", "organiser", "storage", "compartment", "divider", "box with dividers", "storage tray", "parts tray", "organiser tray", "organizer tray", "parts organizer", "parts organiser", "storage box", "divided box", "compartment box", "tool organizer", "tool organiser", "hardware organizer", "hardware organiser", "sorting box", "sorting tray"]
    }
    
    
  ]
}


