{
  "components": [
    {
      "id": "metric_bolt",
      "includes": ["BOSL/constants.scad", "BOSL/metric_screws.scad"],
      "module": "metric_bolt",
      "params": [
        { "name": "size", "type": "int", "unit": "mm", "required": true, "synonyms": ["m", "size", "diameter", "thread", "m-size"] },
        { "name": "l", "type": "float", "unit": "mm", "required": true, "synonyms": ["length", "long", "l"] },
        { "name": "coarse", "type": "bool", "default": true, "synonyms": ["coarse", "course", "fine"] }
      ],
      "intent_keywords": ["bolt", "screw", "cap", "fastener"]
    },
    {
      "id": "metric_nut",
      "includes": ["BOSL/constants.scad", "BOSL/metric_screws.scad"],
      "module": "metric_nut",
      "params": [
        { "name": "size", "type": "int", "unit": "mm", "required": true, "synonyms": ["m", "size", "diameter", "thread", "m-size"] }
      ],
      "intent_keywords": ["nut", "hex nut", "lock nut"]
    },
    {
      "id": "cuboid",
      "includes": ["BOSL/constants.scad", "BOSL/shapes.scad"],
      "module": "cuboid",
      "params": [
        { "name": "size", "type": "float[]", "unit": "mm", "required": true, "synonyms": ["size", "dimensions", "length width height", "lwh"] },
        { "name": "fillet", "type": "float", "unit": "mm", "required": false, "synonyms": ["fillet", "round", "radius"] },
        { "name": "chamfer", "type": "float", "unit": "mm", "required": false, "synonyms": ["chamfer", "bevel"] }
      ],
      "intent_keywords": ["cuboid", "cube", "rectangular", "solid block", "basic shape"]
    },
    {
      "id": "cyl",
      "includes": ["BOSL/constants.scad", "BOSL/shapes.scad"],
      "module": "cyl",
      "params": [
        { "name": "l", "type": "float", "unit": "mm", "required": true, "synonyms": ["length", "l", "h", "long"] },
        { "name": "d", "type": "float", "unit": "mm", "required": true, "synonyms": ["diameter", "d", "od"] }
      ],
      "intent_keywords": ["cyl", "cylinder", "pipe"]
    },
    {
      "id": "trapezoidal_threaded_rod",
      "includes": ["BOSL/constants.scad", "BOSL/threading.scad"],
      "module": "trapezoidal_threaded_rod",
      "params": [
        { "name": "d",             "type": "float", "unit": "mm",      "required": true,  "synonyms": ["diameter", "d", "od", "width"] },
        { "name": "l",             "type": "float", "unit": "mm",      "required": true,  "synonyms": ["length", "l", "long"] },
        { "name": "pitch",         "type": "float", "unit": "mm",      "required": true,  "synonyms": ["pitch", "lead", "thread pitch"] },
        { "name": "thread_depth",  "type": "float", "unit": "mm",      "required": false, "default": "pitch/2", "synonyms": ["depth", "thread depth"] },
        { "name": "thread_angle",  "type": "float", "unit": "degree",  "required": false, "default": 14.5,      "synonyms": ["angle", "pressure angle", "profile angle"] }
      ],
      "intent_keywords": [
        "threaded rod",
        "threaded-rod",
        "trapezoidal",
        "acme",
        "acme rod",
        "lead screw",
        "leadscrew",
        "square thread",
        "screw rod",
        "thread"
      ]
    },
    {
      "id": "sphere",
      "module": "sphere",
      "includes": [],
      "params": [
        { "name": "r", "type": "float", "unit": "mm", "required": true, "synonyms": ["radius","size", "r="] }
      ],
      "intent_keywords": ["sphere", "ball", "circle"]
    },
    {
      "id": "gear",
      "includes": ["BOSL/constants.scad", "BOSL/involute_gears.scad"],
      "module": "gear",
      "params": [
        { "name": "mm_per_tooth",   "type": "float", "unit": "mm", "required": true,  "synonyms": ["circular pitch", "circular_pitch", "mm per tooth", "mm-per-tooth", "cp"] },
        { "name": "number_of_teeth","type": "int",   "unit": "",   "required": true,  "synonyms": ["teeth", "tooth_count", "z"] },
        { "name": "thickness",      "type": "float", "unit": "mm", "required": true,  "synonyms": ["thickness", "face width", "width"] },
        { "name": "hole_diameter",  "type": "float", "unit": "mm", "required": true,  "synonyms": ["bore", "inner diameter", "id", "shaft hole"] }
      ],
      "intent_keywords": ["gear", "spur gear", "helical gear", "involute", "cog", "toothed wheel"]
    },
    {
      "id": "tray",
      "includes": ["tray.scad"],
      "module": "tray",
      "params": [
        { "name": "dimensions",     "type": "float[]", "unit": "mm", "required": true,  "synonyms": ["size", "dimensions", "length width height", "lwh"] },
        { "name": "thickness",      "type": "float",   "unit": "mm", "required": false, "default": 2,     "synonyms": ["wall thickness", "thickness", "wall"] },
        { "name": "n_columns",      "type": "int",     "unit": "",   "required": false, "default": 1,     "synonyms": ["columns", "col", "c"] },
        { "name": "n_rows",         "type": "int",     "unit": "",   "required": false, "default": 1,     "synonyms": ["rows", "row", "r"] },
        { "name": "curved",         "type": "bool",    "unit": "",   "required": false, "default": true,  "synonyms": ["curved", "rounded", "smooth"] },
        { "name": "bottom_thickness", "type": "float", "unit": "mm", "required": false, "default": "thickness", "synonyms": ["bottom", "base thickness"] },
        { "name": "dividers_height", "type": "float",  "unit": "mm", "required": false, "default": "height", "synonyms": ["divider height", "separator height"] },
        { "name": "dividers_thickness", "type": "float", "unit": "mm", "required": false, "default": "thickness", "synonyms": ["divider thickness", "separator thickness"] }
      ],
      "intent_keywords": ["grid", "compartment", "compartments", "divider", "dividers", "organizer", "organiser", "storage box", "storage tray", "divided box", "compartment box", "box with dividers", "box with grid", "box with compartments", "parts tray", "parts organizer", "parts organiser", "tool organizer", "tool organiser", "hardware organizer", "hardware organiser", "sorting box", "sorting tray", "tray", "storage"]
    },
    {
      "id": "slider",
      "includes": ["BOSL2/std.scad", "BOSL2/sliders.scad"],
      "module": "slider",
      "params": [
        { "name": "l", "type": "float", "unit": "mm", "required": true, "synonyms": ["length","l","long","height","h"] },
        { "name": "base", "type": "float", "unit": "mm", "required": true, "synonyms": ["base","base width","inner width","slot width"] },
        { "name": "wall", "type": "float", "unit": "mm", "required": true, "default": 4, "synonyms": ["wall","wall thickness","thickness"] }
      ],
      "intent_keywords": ["slider","linear slider","u-channel","slide block","carriage"]
    },
    {
      "id": "rail",
      "includes": ["BOSL2/std.scad", "BOSL2/sliders.scad"],
      "module": "rail",
      "params": [
        { "name": "l", "type": "float", "unit": "mm", "required": true, "synonyms": ["length","l","long","height","h"] },
        { "name": "w", "type": "float", "unit": "mm", "required": true, "synonyms": ["width","w","rail width","bar width"] },
        { "name": "h", "type": "float", "unit": "mm", "required": true, "synonyms": ["height","h","rail height","bar height"] }
      ],
      "intent_keywords": ["rail","slide rail","linear rail","track"]
    },
    {
      "id": "tube",
      "includes": ["BOSL2/std.scad"],
      "module": "tube",
      "params": [
        { "name": "h", "type": "float", "unit": "mm", "required": true, "synonyms": ["height","h","length","l"] },
        { "name": "od", "type": "float", "unit": "mm", "required": true, "synonyms": ["outer diameter","od","outer_diameter"] },
        { "name": "id", "type": "float", "unit": "mm", "required": false, "default": "od-2", "synonyms": ["inner diameter","id","bore","inner_diameter"] }
      ],
      "intent_keywords": ["tube","pipe","spacer","bushing","ring"]
    },
    {
      "id": "rect_tube",
      "includes": ["BOSL2/std.scad"],
      "module": "rect_tube",
      "params": [
        { "name": "size", "type": "float[]", "unit": "mm", "required": true, "synonyms": ["size","dimensions","length width height","lwh"] },
        { "name": "wall", "type": "float", "unit": "mm", "required": true, "synonyms": ["wall","wall thickness","thickness"] },
        { "name": "h", "type": "float", "unit": "mm", "required": false, "default": "size[2]", "synonyms": ["height","h"] }
      ],
      "intent_keywords": ["rectangular tube","hollow box","beam","frame"]
    },
    {
      "id": "wedge",
      "includes": ["BOSL2/std.scad"],
      "module": "wedge",
      "params": [
        { "name": "size1", "type": "float[]", "unit": "mm", "required": true, "synonyms": ["size1","base1","side1"] },
        { "name": "size2", "type": "float[]", "unit": "mm", "required": true, "synonyms": ["size2","base2","side2"] },
        { "name": "h", "type": "float", "unit": "mm", "required": true, "synonyms": ["height","h"] }
      ],
      "intent_keywords": ["wedge","triangular prism","ramp"]
    },
    {
      "id": "pyramid",
      "includes": ["BOSL2/std.scad"],
      "module": "pyramid",
      "params": [
        { "name": "size", "type": "float[]", "unit": "mm", "required": true, "synonyms": ["size","dimensions","length width","base size"] },
        { "name": "h", "type": "float", "unit": "mm", "required": true, "synonyms": ["height","h"] }
      ],
      "intent_keywords": ["pyramid","tapered block","cone frustum"]
    },
    {
      "id": "rack",
      "includes": ["BOSL/constants.scad", "BOSL/involute_gears.scad"],
      "module": "rack",
      "params": [
        { "name": "mm_per_tooth", "type": "float", "unit": "mm", "required": true, "synonyms": ["circular pitch","mm per tooth","cp"] },
        { "name": "number_of_teeth", "type": "int", "unit": "", "required": true, "synonyms": ["teeth","tooth_count","z"] },
        { "name": "thickness", "type": "float", "unit": "mm", "required": true, "synonyms": ["thickness","height"] }
      ],
      "intent_keywords": ["gear rack","rack","linear gear"]
    }
    
    
    
  ]
}


